---
title: "Untitled"
output: html_document
date: "2023-03-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#live coding for mpm 207, linear regression

library(ggplot2)

# Set the number of observations
n <- 100

# Set the true intercept and slope
intercept <- 2
slope <- 3

# Simulate predictor variable
x <- rnorm(n, mean = 3)

# Simulate response variable
error <- rnorm(n, mean = 0, sd = 2)
y <- intercept + slope * x + error

# Create a data frame of x and y
dsim <- data.frame(x, y)

# Plot the simulated data using ggplot2
ggplot(dsim, aes(x = x, y = y)) +
  geom_point() +
  labs(title = "Simulated Data for Linear Model", x = "Predictor Variable (X)", y = "Response Variable (Y)")

# Fit a linear model to the simulated data
model <- lm(y ~ x)

# Print the model coefficients
summary(model)


# Plot the simulated data and the fitted line using ggplot2 
ggplot(dsim, aes(x = x, y = y)) +
  geom_point(alpha = .5) +
  labs(title = "Simulated Data for Linear Model", x = "Predictor Variable (X)", y = "Response Variable (Y)") +
  geom_abline(intercept = coef(model)[1], slope = coef(model)[2])  + 
  theme_bw()
```

